import FWCore.ParameterSet.Config as cms

skim = cms.EDFilter("Hplus2hwWithTopAnalysisSkim",
                    Verbose        = cms.bool(False),
                    TriggerResults = cms.InputTag("TriggerResults::HLT"),
                    HLTPaths       = cms.vstring(), # don't skim based on Trigger Bits
                    HLTPaths_all   = cms.vstring("HLT_AK8PFJet360_TrimMass30_v",
                                                 "HLT_AK8PFJet400_TrimMass30_v", 
                                                 "HLT_AK8PFHT750_TrimMass50_v", 
                                                 "HLT_AK8PFHT800_TrimMass50_v", 
                                                 "HLT_AK8DiPFJet300_200_TrimMass30_BTagCSV_p20_v", 
                                                 "HLT_AK8DiPFJet280_200_TrimMass30_BTagCSV_p087_v", 
                                                 "HLT_AK8DiPFJet300_200_TrimMass30_BTagCSV_p087_v", 
                                                 "HLT_AK8DiPFJet300_200_TrimMass30_v", 
                                                 "HLT_AK8PFHT700_TrimR0p1PT0p03Mass50_v", 
                                                 "HLT_AK8PFHT650_TrimR0p1PT0p03Mass50_v",
                                                 "HLT_AK8PFHT600_TrimR0p1PT0p03Mass50_BTagCSV_p20_v", 
                                                 "HLT_AK8DiPFJet280_200_TrimMass30_v", 
                                                 "HLT_AK8DiPFJet250_200_TrimMass30_v", 
                                                 "HLT_AK8DiPFJet280_200_TrimMass30_BTagCSV_p20_v", 
                                                 "HLT_AK8DiPFJet250_200_TrimMass30_BTagCSV_p20_v", 
                                                 "HLT_CaloJet260_v", 
                                                 "HLT_CaloJet500_NoJetID_v", 
                                                 "HLT_Dimuon13_PsiPrime_v", 
                                                 "HLT_Dimuon13_Upsilon_v", 
                                                 "HLT_Dimuon20_Jpsi_v", 
                                                 "HLT_DoubleEle24_22_eta2p1_WPLoose_Gsf_v", 
                                                 "HLT_DoubleEle25_CaloIdL_GsfTrkIdVL_v",
                                                 "HLT_DoubleEle33_CaloIdL_v",
                                                 "HLT_DoubleEle33_CaloIdL_MW_v", 
                                                 "HLT_DoubleEle33_CaloIdL_GsfTrkIdVL_MW_v",
                                                 "HLT_DoubleEle33_CaloIdL_GsfTrkIdVL_v", 
                                                 "HLT_DoubleMediumCombinedIsoPFTau35_Trk1_eta2p1_Reg_v", 
                                                 "HLT_DoubleTightCombinedIsoPFTau35_Trk1_eta2p1_Reg_v", 
                                                 "HLT_DoubleMediumCombinedIsoPFTau40_Trk1_eta2p1_Reg_v", 
                                                 "HLT_DoubleTightCombinedIsoPFTau40_Trk1_eta2p1_Reg_v", 
                                                 "HLT_DoubleMediumCombinedIsoPFTau40_Trk1_eta2p1_v", 
                                                 "HLT_DoubleTightCombinedIsoPFTau40_Trk1_eta2p1_v", 
                                                 "HLT_DoubleMediumIsoPFTau35_Trk1_eta2p1_Reg_v", 
                                                 "HLT_DoubleMediumIsoPFTau40_Trk1_eta2p1_Reg_v",
                                                 "HLT_DoubleMediumIsoPFTau40_Trk1_eta2p1_v",
                                                 "HLT_DoubleEle37_Ele27_CaloIdL_GsfTrkIdVL_v",
                                                 "HLT_DoubleMu0_v", 
                                                 "HLT_DoubleMu4_3_Bs_v",
                                                 "HLT_DoubleMu4_3_Jpsi_Displaced_v",
                                                 "HLT_DoubleMu4_JpsiTrk_Displaced_v",
                                                 "HLT_DoubleMu4_LowMassNonResonantTrk_Displaced_v",
                                                 "HLT_DoubleMu3_Trk_Tau3mu_v", 
                                                 "HLT_DoubleMu4_PsiPrimeTrk_Displaced_v",
                                                 "HLT_Mu7p5_L2Mu2_Jpsi_v", 
                                                 "HLT_Mu7p5_L2Mu2_Upsilon_v", 
                                                 "HLT_Mu7p5_Track2_Jpsi_v", 
                                                 "HLT_Mu7p5_Track3p5_Jpsi_v", 
                                                 "HLT_Mu7p5_Track7_Jpsi_v", 
                                                 "HLT_Mu7p5_Track2_Upsilon_v", 
                                                 "HLT_Mu7p5_Track3p5_Upsilon_v", 
                                                 "HLT_Mu7p5_Track7_Upsilon_v", 
                                                 "HLT_Dimuon0er16_Jpsi_NoOS_NoVertexing_v", 
                                                 "HLT_Dimuon0er16_Jpsi_NoVertexing_v", 
                                                 "HLT_Dimuon6_Jpsi_NoVertexing_v", 
                                                 "HLT_Photon150_v", 
                                                 "HLT_Photon90_CaloIdL_HT300_v", 
                                                 "HLT_HT250_CaloMET70_v", 
                                                 "HLT_DoublePhoton60_v",
                                                 "HLT_DoublePhoton85_v", 
                                                 "HLT_Ele17_Ele8_Gsf_v", 
                                                 "HLT_Ele20_eta2p1_WPLoose_Gsf_LooseIsoPFTau28_v", 
                                                 "HLT_Ele22_eta2p1_WPLoose_Gsf_LooseIsoPFTau29_v", 
                                                 "HLT_Ele22_eta2p1_WPLoose_Gsf_v", 
                                                 "HLT_Ele22_eta2p1_WPLoose_Gsf_LooseIsoPFTau20_SingleL1_v", 
                                                 "HLT_Ele23_WPLoose_Gsf_v", 
                                                 "HLT_Ele23_WPLoose_Gsf_WHbbBoost_v", 
                                                 "HLT_Ele24_eta2p1_WPLoose_Gsf_v",
                                                 "HLT_Ele24_eta2p1_WPLoose_Gsf_LooseIsoPFTau20_v", 
                                                 "HLT_Ele24_eta2p1_WPLoose_Gsf_LooseIsoPFTau20_SingleL1_v", 
                                                 "HLT_Ele24_eta2p1_WPLoose_Gsf_LooseIsoPFTau30_v", 
                                                 "HLT_Ele25_WPTight_Gsf_v",
                                                 "HLT_Ele25_eta2p1_WPLoose_Gsf_v",
                                                 "HLT_Ele25_eta2p1_WPTight_Gsf_v",
                                                 "HLT_Ele27_WPLoose_Gsf_v",
                                                 "HLT_Ele27_WPLoose_Gsf_WHbbBoost_v", 
                                                 "HLT_Ele27_WPTight_Gsf_v",
                                                 "HLT_Ele27_WPTight_Gsf_L1JetTauSeeded_v", 
                                                 "HLT_Ele27_eta2p1_WPLoose_Gsf_v", 
                                                 "HLT_Ele27_eta2p1_WPLoose_Gsf_LooseIsoPFTau20_SingleL1_v", 
                                                 "HLT_Ele27_eta2p1_WPTight_Gsf_v", 
                                                 "HLT_Ele30_WPTight_Gsf_v", 
                                                 "HLT_Ele30_eta2p1_WPLoose_Gsf_v", 
                                                 "HLT_Ele30_eta2p1_WPTight_Gsf_v", 
                                                 "HLT_Ele32_WPTight_Gsf_v", 
                                                 "HLT_Ele32_eta2p1_WPLoose_Gsf_v", 
                                                 "HLT_Ele32_eta2p1_WPLoose_Gsf_LooseIsoPFTau20_SingleL1_v", 
                                                 "HLT_Ele32_eta2p1_WPTight_Gsf_v", 
                                                 "HLT_Ele35_WPLoose_Gsf_v",
                                                 "HLT_Ele35_CaloIdVT_GsfTrkIdT_PFJet150_PFJet50_v",
                                                 "HLT_Ele36_eta2p1_WPLoose_Gsf_LooseIsoPFTau20_SingleL1_v", 
                                                 "HLT_Ele45_WPLoose_Gsf_v",
                                                 "HLT_Ele45_WPLoose_Gsf_L1JetTauSeeded_v", 
                                                 "HLT_Ele45_CaloIdVT_GsfTrkIdT_PFJet200_PFJet50_v", 
                                                 "HLT_Ele105_CaloIdVT_GsfTrkIdT_v", 
                                                 "HLT_Ele30WP60_SC4_Mass55_v", 
                                                 "HLT_Ele30WP60_Ele8_Mass55_v", 
                                                 "HLT_HT200_v", 
                                                 "HLT_HT275_v", 
                                                 "HLT_HT325_v", 
                                                 "HLT_HT425_v", 
                                                 "HLT_HT575_v", 
                                                 "HLT_HT410to430_v", 
                                                 "HLT_HT430to450_v", 
                                                 "HLT_HT450to470_v", 
                                                 "HLT_HT470to500_v", 
                                                 "HLT_HT500to550_v", 
                                                 "HLT_HT550to650_v", 
                                                 "HLT_HT650_v", 
                                                 "HLT_Mu16_eta2p1_MET30_v", 
                                                 "HLT_IsoMu16_eta2p1_MET30_v", 
                                                 "HLT_IsoMu16_eta2p1_MET30_LooseIsoPFTau50_Trk30_eta2p1_v", 
                                                 "HLT_IsoMu17_eta2p1_v", 
                                                 "HLT_IsoMu17_eta2p1_LooseIsoPFTau20_v", 
                                                 "HLT_IsoMu17_eta2p1_LooseIsoPFTau20_SingleL1_v", 
                                                 "HLT_DoubleIsoMu17_eta2p1_v",
                                                 "HLT_DoubleIsoMu17_eta2p1_noDzCut_v", 
                                                 "HLT_IsoMu18_v", 
                                                 "HLT_IsoMu19_eta2p1_LooseIsoPFTau20_v", 
                                                 "HLT_IsoMu19_eta2p1_LooseIsoPFTau20_SingleL1_v", 
                                                 "HLT_IsoMu19_eta2p1_MediumIsoPFTau32_Trk1_eta2p1_Reg_v", 
                                                 "HLT_IsoMu19_eta2p1_LooseCombinedIsoPFTau20_v", 
                                                 "HLT_IsoMu19_eta2p1_MediumCombinedIsoPFTau32_Trk1_eta2p1_Reg_v", 
                                                 "HLT_IsoMu19_eta2p1_TightCombinedIsoPFTau32_Trk1_eta2p1_Reg_v", 
                                                 "HLT_IsoMu21_eta2p1_MediumCombinedIsoPFTau32_Trk1_eta2p1_Reg_v", 
                                                 "HLT_IsoMu21_eta2p1_TightCombinedIsoPFTau32_Trk1_eta2p1_Reg_v", 
                                                 "HLT_IsoMu20_v", 
                                                 "HLT_IsoMu21_eta2p1_LooseIsoPFTau20_SingleL1_v", 
                                                 "HLT_IsoMu21_eta2p1_LooseIsoPFTau50_Trk30_eta2p1_SingleL1_v", 
                                                 "HLT_IsoMu21_eta2p1_MediumIsoPFTau32_Trk1_eta2p1_Reg_v", 
                                                 "HLT_IsoMu22_v", 
                                                 "HLT_IsoMu22_eta2p1_v", 
                                                 "HLT_IsoMu24_v"),
                    ### PF Candidates
                    PackedCandidatesCollection = cms.InputTag("packedPFCandidates"),
                    ### Vertex
                    VertexCollection = cms.InputTag("offlineSlimmedPrimaryVertices"),
                    ### Electrons (https://twiki.cern.ch/twiki/bin/view/CMS/CutBasedElectronIdentificationRun2)
                    ElectronCollection   = cms.InputTag("slimmedElectrons"),
                    ElectronRhoSource    = cms.InputTag("fixedGridRhoFastjetCentralNeutral"),
                    ElectronID           = cms.string("cutBasedElectronID-Spring15-25ns-V1-standalone-veto"),
                    ElectronMVA          = cms.InputTag("electronMVAValueMapProducer:ElectronMVAEstimatorRun2Spring16GeneralPurposeV1Values"),
                    ElectronMiniRelIsoEA = cms.double(1.0),
                    ElectronUseTightID   = cms.bool(False),     # True = Tight MVA WP, False = Loose MVA WP
                    ElectronPtCut        = cms.double(10.0),
                    ElectronEtaCut       = cms.double(3.0),
                    ElectronNCut         = cms.int32(0),        # This is checked ONLY if the "LeptonNCut" is satisfied
                    ### Muons (https://twiki.cern.ch/twiki/bin/view/CMS/SWGuideMuonIdRun2)
                    MuonCollection       = cms.InputTag("slimmedMuons"),
                    MuonID               = cms.string("Loose"), # [options: Loose, Medium, Tight]
                    MuonMiniRelIsoEA     = cms.double(1.0),     # [default: 0.4]
                    MuonPtCut            = cms.double(10.0),
                    MuonEtaCut           = cms.double(3.0),
                    MuonNCut             = cms.int32(0),        # This is checked ONLY if the "LeptonNCut" is satisfied
                    ### Leptons (Electrons or Muons)
                    LeptonNCut           = cms.int32(0),        # Concerns the above-defined electrons and muon selections
                    ### Taus
                    TauCollection        = cms.InputTag("slimmedTaus"),
                    TauDiscriminators    = cms.vstring("decayModeFinding",
                                                       "byVLooseIsolationMVArun2v1DBoldDMwLT",),
                    TauPtCut             = cms.double(20),
                    TauEtaCut            = cms.double(3.0),
                    TauNCut              = cms.int32(0),
                    ### Jets (https://twiki.cern.ch/twiki/bin/viewauth/CMS/JetID#Recommendations_for_13_TeV_data)
                    JetCollection        = cms.InputTag("slimmedJets"),
                    JetUserFloats        = cms.vstring(),       # DISABLED
                    # JetUserFloats        = cms.vstring("pileupJetId:fullDiscriminant",),
                    JetEtCut             = cms.double(30.0),
                    JetEtaCut            = cms.double(2.4),
                    JetNCut              = cms.int32(0),
                    )
